# conky &

## wallpaper

# feh --bg-scale /home/ryz/pics/wallpaper/200709054955-2178.jpg &
feh --bg-scale /home/ryz/pics/wallpaper/dualscreen/01341_headingwest_2560x1024.jpg &

## misc

unclutter -idle 1 &

## statusbars

#/usr/local/bin/xmobar ~/.xmobarrc &
# /home/ryz/scripts/dzen | dzen2 -ta r -fn '-*-fixed-*-*-*-*-9-*-*-*-*-*-*-*' -bg '#2c2c32' -fg 'grey70' -p -e '' &

## terminals

#urxvt &

## wm

$HOME/bin/xmonad
#exec /usr/local/bin/dwm
#exec awesome 
